files:
  - source: /Assets/Localization/Translations.csv
    translation: '%original_path%%original_file_name%'
    multilingual_spreadsheet: '1'
    first_line_contains_header: '1'
    scheme: 'identifier,source_phrase,de,fr,da'
