files:
  - source: /Assets/Localization/Translations.csv
    translation: /Assets/Localization/Translations/Languages/%two_letters_code%
    first_line_contains_header: '1'
    scheme: 'identifier,source_or_translation'
