"files" : [
  {
    "source" : "/Assets/Localization/Translations.csv",
    "translation" : "/Assets/Localization/Translations.csv",
    "first_line_contains_header" : true,
    "scheme" : "identifier,source_phrase,de,fr,da"
  }
]