files:
  - source: /Assets/Localization/Translations/
    translation: /Assets/Localization/Translations/%two_letters_code%.csv
    first_line_contains_header: '1'
    scheme: 'identifier,context,source_or_translation'
