files:
  - source: /Assets/Localization/Translations/**/en.csv
    translation: /Assets/Localization/Translations/%original_path%/%two_letters_code%.csv
    first_line_contains_header: '1'
    scheme: 'identifier,context,source_or_translation'
